### ISSUE TITLE
Some Questions About Kernel Module

### ISSUE THREAD

**Issue by fanguannan0706** [OP-TEE/optee_linuxdriver#24]
Hi, I'd like to write a device driver which need to connect to tee. But the kernel module made a mistake : "kernel panic - not syncing : BUG!" Maybe It because I called the functions in "tee_kernel_api.c",such as TEEC_InitializeContext. It makes me confused, why the TEE_TZ_DEVICE_NAME is defined "opteearm3200"? it may be "opteearmtz00". And if the functions can work on the 64-bit platform?

**Comment by pascal-brand-st-dev** [comment]
*why the TEE_TZ_DEVICE_NAME is defined "opteearm3200"?*

* You are right. This is fixed in #28 

*And if the functions can work on the 64-bit platform?* 

* Yes.
