### ISSUE TITLE
Some Questions About tee_kernel_api

### ISSUE THREAD

**Issue by fanguannan0706** [OP-TEE/optee_linuxdriver#34]
Hi,
I really want to write a module using functions in the tee_kernel_api.c， But, It can't work. I guess the reason is the functions can't work on the 64 bit platform, because I find there are some notes like this 	/* TODO fixme will not work on 64-bit platform */. I tried to change type of fd from int to uint64_t, but it have no effect. So, I have to ask you for help.

**Comment by jenswi-linaro** [comment]
Hi,

If you change the type of `fd` in `TEEC_Context` it's an API change for user space so TEE Client API lib and tee-supplicant need to be updated accordingly. What kind of errors is it you get, `BUG_ON(ctx != (struct tee_context *)(uintptr_t)context->fd)`?

Regards,
Jens

**Comment by pascal-brand-st** [comment]
Question has been answered, please re-open in case you have additional questions.

Please note that https://github.com/OP-TEE/optee_linuxdriver is deprecated. The generic driver is now used (cf. https://github.com/OP-TEE/optee_os/blob/master/CHANGELOG.md#op-tee---version-200)
