### ISSUE TITLE
Question about tee_session.c _update_client_tee_cmd

### ISSUE THREAD

**Issue by acy54321** [OP-TEE/optee_linuxdriver#46]
In the code  _update_client_tee_cmd. I have some uncertainty about here. _update_client_tee_cmd is copy result when OP-TEE OS return,but in case TEEC_MEMREF_TEMP_OUTPUT and TEEC_MEMREF_TEMP_INOUT in first "if size_new != cmd_io->op->params[idx].tmpref.size" will use tee_put_user re-update value of cmd_io->op->params[idx].tmpref.size. But in the following judgment of "if (size_new > cmd_io->op->params[idx].tmpref.size)" will never be True. "dev_err" will not occur . The following behavior of tee_copy_to_user (ctx, cmd_io->op->params[idx].tmpref.buffer, cmd->param.params[idx].shm->kaddr, size_new) will copy the risk of over boundary??

**Comment by pascal-brand-st-dev** [comment]
You're right, we should test before updating the value.

@jbech-linaro Should we fix it as we're going to use the new Generic Driver?

**Comment by pascal-brand-st** [comment]
optee_linuxdriver is no more the official linux driver of OP-TEE. New driver can be found in https://github.com/linaro-swg/linux/tree/optee
